name: APK Uretici
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Sistem Araclarini Kur
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install --upgrade Cython==0.29.33 buildozer
      - name: APK Paketle (Buildozer)
        run: |
          buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,flet==0.8.2,pandas,openpyxl,numpy/' buildozer.spec
          sed -i 's/#android.api = 31/android.api = 33/' buildozer.spec
          sed -i 's/p4a.bootstrap = sdl2/p4a.bootstrap = /' buildozer.spec
          buildozer -v android debug
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4
        with:
          name: KPSS_Uygulamasi_APK
          path: bin/*.apk
